### ISSUE TITLE
Getting Error 403 from Medium Feed

### ISSUE THREAD

**Issue by kevinfengcs88** [gautamkrishnar/blog-post-workflow#113] opened 2022-01-11 03:49 UTC
Here is a list of the most recent workflows; was able to run fine 7 times, but on the 8th and 9th scheduled attempts, they failed. On the 10th (manual run), it also failed. 

![image](https://user-images.githubusercontent.com/80129996/148877753-7130c7d8-448b-431d-8351-af7d30d90cf4.png)

Investigating why they failed, I can see the following two annotations for each of the failures:

![image](https://user-images.githubusercontent.com/80129996/148877831-1306726b-66a3-454d-a294-883239bbd3a2.png)

Although it's not a 404, visiting https://kevinfeng-cs88.medium.com/feed seems to yield no issue. I don't believe Medium would forbid access from the workflow client. The following is the link to the .yml file, which I believe I've set up correctly (it was able to run successfully 7 times after all): https://github.com/kevinfengcs88/kevinfengcs88/blob/main/.github/workflows/blog-post-workflow.yml

**Comment by kaustubhgupta** [comment] 2022-01-11 05:19
Same, my workflow has been running for 9-10 months, but today it got into 403 error. Any fix would be highly appreciated. https://github.com/kaustubhgupta/kaustubhgupta/actions/workflows/blog-updater.yml

**Comment by gautamkrishnar** [comment] 2022-01-11 07:10
@kaustubhgupta @kevinfengcs88 thanks for reporting.  As you can see from the error logs that this is a medium issue. Please report the same to medium support and ask them why this is happening:
```
Error: https://medium.com/feed/@kaustubhgupta1828 runner failed, please verify the configuration. Error:
Error: Error: Status code 403
```

This can't be fixed in the blog post workflow since this is triggered by the medium's backed. Keeping this issue open so that others who face the same issue might be aware of this.

**Comment by gautamkrishnar** [comment] 2022-01-11 07:14
> e. I don't believe Medium would forbid access from the workflow client. The following is the link to the .yml file, which I believe I've set up correctly (it was able to run successfully 7 times after all): https://github.com/kevinfengcs88/kevinfengcs88/blob/main/.github/workflows/blog-post-workflow.yml

Medium might've blocked the public IP of Github.

**Comment by gautamkrishnar** [comment] 2022-01-11 07:44
@kaustubhgupta @kevinfengcs88 As a workaround you can use some of the feed aggregators.  It will act as a proxy for your actual feeds.

https://www.lifewire.com/rss-aggregator-tools-3486469

For example @kaustubhgupta you can use this URL for your feeds (https://www.analyticsvidhya.com/blog/author/kaustubh1828/feed/, https://medium.com/feed/@kaustubhgupta1828): http://www.rssmix.com/u/13564959/rss.xml  (this uses http://www.rssmix.com/ aggregator)

For @kevinfengcs88 since you only have one feed URL (https://kevinfeng-cs88.medium.com/feed), you need to do a hack. Most of the feed aggregators require at least two URLs. I just created an empty feed URL that anyone can use as a placeholder for the second URL: `https://raw.githubusercontent.com/gkr-bot/empty-feed/main/empty.xml`.

Giving the following values to http://www.rssmix.com/:
```
https://kevinfeng-cs88.medium.com/feed
https://raw.githubusercontent.com/gkr-bot/empty-feed/main/empty.xml
```
Generates the following URL: http://www.rssmix.com/u/13564977/rss.xml you can use it in your workflow.

**Comment by kevinfengcs88** [comment] 2022-01-11 14:50
> Generates the following URL: `http://www.rssmix.com/u/13565005/rss.xml` you can use it in your workflow.

This RSS mix seems to work, thank you!
![image](https://user-images.githubusercontent.com/80129996/148965165-b528254a-72b7-45e1-9ea6-3a4c6ab6c89c.png)

**Comment by miShelbyT** [comment] 2022-01-11 17:23
> https://raw.githubusercontent.com/gkr-bot/empty-feed/main/empty.xml

This solution worked for my RSS feed too. Thank you for finding a workaround for us, @gautamkrishnar !! <3

**Comment by gautamkrishnar** [comment] 2022-01-12 07:56
Hi Guys, looks like the issue is resolved right now, the medium team had fixed their backend. You can revert back to your original code if you are using the workaround.

![Screenshot 2022-01-12 at 1 24 55 PM](https://user-images.githubusercontent.com/8397274/149086362-e1e66aaf-f348-4b10-a0ae-85f2b84f8394.png)

Please comment here if you are still facing the issue. @miShelbyT @kevinfengcs88 @Edstub207 @mcolladoio

**Comment by mcolladoio** [comment] 2022-01-12 10:03
Revert to previous feed and now, everything is working fine!
Thanks for the advice @gautamkrishnar

**Comment by gautamkrishnar** [comment] 2022-01-12 16:45
Thanks for confirming @mcolladoio, Closing this issue since it is working fine now.

**Closed by gautamkrishnar** 2022-01-12 16:45 UTC

**Comment by miShelbyT** [comment] 2022-01-12 19:11
Thanks to everyone on this thread. It takes a village!! <3

**Comment by kaustubhgupta** [comment] 2022-01-13 07:32
@gautamkrishnar yes the issue is fixed from Medium side. Thanks for suggesting the workarounds! 😄
