### ISSUE TITLE
[Bug]: Error: {"code":1,"outputData":""}

### ISSUE THREAD

**Issue by nil0x42** [gautamkrishnar/blog-post-workflow#60] opened 2021-04-01 11:23 UTC
**Describe the bug**
Since yesterday (2021-03-31 20:00), my blog-post-workflow action fails every hour, with this weird error:
`Error: {"code":1,"outputData":""}`

**Expected behavior**
The job should just succeed, even if there is nothing new to do

**Screenshots**
![Screenshot_2021-04-01_05-52-19](https://user-images.githubusercontent.com/3504393/113249795-ddea0b80-92ae-11eb-815c-aef2d3cf1e3f.png)

**Workflow Yml Used**
```yml
name: Latest Tweets workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # created from twitter search string:
          #   from:nil0x42 min_faves:5 min_retweets:2 -filter:retweets -filter:replies -filter:quote
          feed_list: "https://rss.app/feeds/x4n09N54uqkYSpaC.xml"
          comment_tag_name: LATEST-TWEETS
          item_exec: "post.title = post.title.replace(/(?:\\r\\n|\\r|\\n)/g,' ')"
          title_max_length: 80
          date_format: "mmm dd HH:MM"
          template: "<li>$date <a href='$url'>$title</a></li>$newline"
          tag_post_pre_newline: true
          commit_message: "blog-post-workflow/latest-tweets: update"
          committer_username: latest-tweets
          committer_email: latest-tweets@notamail.co
```

**Additional context**
I've been using this exact workflow for many months and never got any error. And i didn't change anything in the code. But i couldn't figure out how this error started happening

**Comment by gautamkrishnar** [comment] 2021-04-01 11:57
@nil0x42 Will take a look at it thanks for reporting.

**Comment by gautamkrishnar** [comment] 2021-04-01 18:09
Hi @nil0x42 this is due to the service you are using. It is returning random data everytime you fetch it.
![Screenshot 2021-04-01 at 11 37 52 PM](https://user-images.githubusercontent.com/8397274/113336116-83e75580-9343-11eb-93b6-a898c9dfdd18.png)

Please doube check the source. It has some problem.

**Comment by gautamkrishnar** [comment] 2021-04-01 18:52
Digged deeper into the problem this is not a bug of fhe app itself it is mainly due to the handling of the emojis.

Following is the text i got while i ran this workflow two times.
Old value
```
<li>Mar 31 18:34 <a href='https://rss.app/articles/cb4e791f6f6d729c074351566bd3a7c508111d6e1136beb1dab6d555969266d3f70cea0d6adfd96af7a76e7bd7100b9466d76de3c314'>🎇 Coordinate your #bugbounty reconnaissance workflows across multiple devices �...</a></li>
```
New Value from API:
```
<li>Mar 31 18:34 <a href='https://rss.app/articles/cb4e791f6f6d729c074351566bd3a7c508111d6e1136beb1dab6d555969266d3f70cea0d6adfd96af7a76e7bd7100b9466d76de3c314'>🎇 Coordinate your #bugbounty reconnaissance workflows across multiple devices ?...</a></li>
```

This is mainly due to something happeing in node js using the 🔥  emoji in your tweet: https://twitter.com/nil0x42/status/1377245468447625216

I guess this is becasue the emoji is truncated half way. You can increase the trucation limit to fix the issue temporarly.

**Comment by gautamkrishnar** [comment] 2021-04-01 19:50
@nil0x42 fix for this is released on https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.5.5 🎉 You dont have to use the wokarround. It will fixed in the next workflow run.

**Comment by nil0x42** [comment] 2021-04-02 12:19
Hi ! Very interesting bug BTW ! After you pushed new release it stopped failing, but now it just failed again

**Comment by gautamkrishnar** [comment] 2021-04-02 12:33
@nil I can't see any failing workflows here dab

**Comment by gautamkrishnar** [comment] 2021-04-02 12:34
I can't see any failing workflows on your profile. Can you please share the link.

**Closed** 2021-04-02 12:36 UTC
Labels: bug, help wanted
